name: Release
on:
  release:
    types:
      - published
jobs:
  docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/mikbot/lottie-renderer-service:${{ github.ref_name }}
            ghcr.io/mikbot/lottie-renderer-service:latest
  cargo:
    name: Publish to crates.io
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Compile and Install rlottie
        run: ./scripts/build_rlottie.sh
      - uses: actions-rs/cargo@v1
        with:
          command: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

